def madlib():
    adj1 = input("Adjective: ")
    adj2 = input("Adjective: ")
    adj3 = input("Adjective: ")
    adj4 = input("Adjective: ")
    noun1 = input("Noun: ")
    noun2 = input("Noun: ")
    noun3 = input("Noun: ")
    noun4 = input("Noun: ")
    noun5 = input("Noun: ")
    noun6 = input("Noun: ")
    noun_plural = input("Noun plural: ")
    body_part = input("Body part: ")
    body_part2 = input("Body part: ")
    verb = input("Verb: ")
    verb_past = input("Verb (past tense): ")
    verb_past2 = input("Verb (past tense): ")