def madlib():
    number = input("Number: ")
    adj = input("Adjective: ")
    verb = input("Verb: ")
    verb2 = input("Verb: ")
    noun = input("Noun: ")
    noun2 = input("Noun: ")
    noun3 = input("Noun: ")
    noun4 = input("Noun: ")
    noun5 = input("Noun: ")
    noun_plural = input("Noun (plural): ")
    noun_plural_2 = input("Noun (plural): ")
    noun_plural_3 = input("Noun (plural): ")
    sound_important = input("Name of something that sounds important: ")